name: Scrapper

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Script starting
          python3 $GITHUB_WORKSPACE/scrapper.py
          echo ::set-output name=exit_code::$?
          echo Script done
          
      - name: Send SMS
        if: steps.build.outputs.exit_code == 0
        uses: nexmo-community/nexmo-sms-action@master
        env:
          NEXMO_API_KEY: ${{ secrets.NEXMO_API_KEY }}
          NEXMO_API_SECRET: ${{ secrets.NEXMO_API_SECRET }}
        with:
          nexmoNumber: 12262471505
          recipientNumber: 15145548991
          message: "Hey puppies are ready -> http://www.premina.ca/puppage.htm"
